apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.open_weather_api_key }}
  OPENWEATHERMAP_API_KEY: {{ .Values.open_weather_api_key | b64enc  | quote }}
  {{- end }}