{{- if and .Values.ingress.enabled  .Values.ingress.istio}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.ingress.host }}
  gateways:
    - {{ .Values.ingress.gateway }}
  http:
    - match:
        - ignoreUriCase: true
          uri:
          {{- if .Values.ingress.prefix }}
            prefix: {{ .Values.ingress.apiPrefix }}
          {{- else }}
            prefix: /
          {{- end }}
      route:
        - destination:
            host: {{ include "helm.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}